// <auto-generated />
namespace Jobify.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Add_tables_and_relations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_tables_and_relations));
        
        string IMigrationMetadata.Id
        {
            get { return "202105291214204_Add_tables_and_relations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
